<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="inertial_macros.xacro"/>

<!-- Define robot constants -->
  <xacro:property name="base_width" value="0.241"/>
  <xacro:property name="base_length" value="0.32"/>
  <xacro:property name="base_height" value="0.0785"/>

  <xacro:property name="wheel_radius" value="0.079"/>
  <xacro:property name="wheel_width" value="0.084"/>
  <xacro:property name="wheel_ygap" value="0.0437"/>
  <xacro:property name="wheel_zoff" value="0"/>
  <xacro:property name="wheel_front_xoff" value="0.11"/>
  <xacro:property name="wheel_rear_xoff" value="-0.11"/>

<!-- Robot Base -->
  <link name="base_link">
    
  </link>

<!-- Robot Chassis-->
 <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="0 0 0"/>
  </joint>

  <link name="chassis">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="3" x="${base_length}" y=" ${base_width}" z=" ${base_height}">
      <origin xyz= "0 0 0" rpy="0 0 0"/>
    </xacro:inertial_box> 
  </link>

  <gazebo reference="chassis">
    <material>Gazebo/Blue</material>
  </gazebo>

<!-- Robot Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>
  
 <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}"/>
      <origin xyz="${x_reflect*wheel_front_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <link name="${prefix}">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="0.5" radius="${wheel_radius}" length="${wheel_width}">
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
    </link>

    <gazebo reference="${prefix}">
      <material>Gazebo/Gray</material>
    </gazebo>

  </xacro:macro>

  <xacro:wheel prefix="drivewhl_l_r" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="drivewhl_r_r" x_reflect="-1" y_reflect="-1" />
  <xacro:wheel prefix="drivewhl_l_f" x_reflect="1" y_reflect="1" />
  <xacro:wheel prefix="drivewhl_r_f" x_reflect="1" y_reflect="-1" />
   
</robot>
 
