<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">


<!-- Define robot constants -->
  <xacro:property name="base_width" value="0.241"/>
  <xacro:property name="base_length" value="0.32"/>
  <xacro:property name="base_height" value="0.0785"/>

  <xacro:property name="wheel_radius" value="0.079"/>
  <xacro:property name="wheel_width" value="0.084"/>
  <xacro:property name="wheel_ygap" value="0.0437"/>
  <xacro:property name="wheel_zoff" value="0"/>
  <xacro:property name="wheel_front_xoff" value="0.11"/>
  <xacro:property name="wheel_rear_xoff" value="-0.11"/>

<!-- Robot Base -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
  </link>
  
<!-- Robot Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>
  
<!-- LiDAR -->
 <joint name="laser_joint" type="fixed">
     <parent link="base_link"/>
     <child link="laser_frame"/>
     <origin xyz="0 0 0.1" rpy="0 0 0"/>
     <axis xyz="0 0 1" />
 </joint>

 <link name="laser_frame">
	  <visual>
	    <geometry>
		    <cylinder radius="0.0508" length="0.041"/>
	    </geometry>
	    <material name="red">
	    	<color rgba=" 1 0 0 1" />
	    </material>
    </visual>
    <visual>
        <geometry>
      <cylinder radius="0.0508" length="0.041"/>
        </geometry>
        <material name="red">
        <color rgba=" 1 0 0 1" />
        </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.0508" length="0.041"/>
      </geometry>
    </collision>
  </link>
 
 <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_front_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_front_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="drivewhl_l_r" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="drivewhl_r_r" x_reflect="-1" y_reflect="-1" />
  <xacro:wheel prefix="drivewhl_l_f" x_reflect="1" y_reflect="1" />
  <xacro:wheel prefix="drivewhl_r_f" x_reflect="1" y_reflect="-1" />
  

  
</robot>
 
